### ISSUE TITLE
上拉不能加载更多，会直接多出来显示一个尾部控件

### ISSUE THREAD

**Issue by Arduns** [zhou-you/EasyXRecyclerView#12]

**Comment by zhou-you** [comment]
请看我的demo是否有同样的问题

**Comment by Arduns** [comment]
android {
    compileSdkVersion 28
    defaultConfig {
        applicationId ""
        minSdkVersion 24
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

loadmore 目前试了很多方法footer怎么改就是不会隐藏，是否一定要退回到25

**Comment by zhou-you** [comment]
目前在我demo上好像并没有这个问题，28我还没尝试过
