### ISSUE TITLE
一个项目接入、运行无法找到 类

### ISSUE THREAD

**Issue by weizheng15828676432** [zhou-you/EasyXRecyclerView#4]
Caused by: android.view.InflateException: Binary XML file line #190: Binary XML file line #190: Error inflating class com.zhouyou.recyclerview.XRecyclerView   

是依赖冲突来吗？还是什么 buildToolsVersion  版本问题！

**Comment by zhou-you** [comment]
用我的demo测试会不会有这个问题？有可能是遗留问题，看看是否是依赖了我的库 又依赖了XRecyclerView库

**Comment by weizheng15828676432** [comment]
是依赖了XRecyclerView  我测试你的dome  添加XRecyclerView  依赖 并不会有 找不到类这个问题。两个库不能同时使用吗？

**Comment by weizheng15828676432** [comment]
之前使用过XRecyclerView 并没有删除。

**Comment by zhou-you** [comment]
用我的了就没必要再用Xrecyclerview

**Comment by weizheng15828676432** [comment]
好的
