### ISSUE TITLE
有子项为list，有加头布局和脚布局，下拉刷新卡顿,

### ISSUE THREAD

**Issue by tarooo** [zhou-you/EasyXRecyclerView#6]
适配器是继承GroupedAppendStateRecyclerViewAdapter，XRecyclerView没有其他设置，下拉刷新顿一下再实现下拉刷新
今天发现如果是size是0的时候setGroups（list）会出错，adapter.removeAll()也是无效的

**Comment by tarooo** [comment]
今天发现如果是size是0的时候setGroups（list）会出错

**Comment by zhou-you** [comment]
能把你的错误贴出来吗？如果你用的是GroupedAppendStateRecyclerViewAdapter适配器表示的是追加状态适配器。建议使用addAppendGroups。我自己设置adapter.setGroups(new ArrayList<GroupBean>());size也是为0并没有出错。
